#!/bin/bash
########################################################################
# by PINPEREPETTE (the Pirate) #
########################################################################
# This program is free software; you can redistribute it and/or modify #
# it under the terms of the GNU General Public License as published by #
# the Free Software Foundation; either version 2 of the License, or #
# (at your option) any later version. #
# #
# This program is distributed in the hope that it will be useful, #
# but WITHOUT ANY WARRANTY; without even the implied warranty of #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the #
# GNU General Public License for more details. #
# #
# You should have received a copy of the GNU General Public License #
# along with this program; if not, write to the Free Software #
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, #
# MA 02110-1301, USA. #
############################# DISCALIMER ###############################
# Usage of this software for probing/attacking targets without prior #
# mutual consent, is illegal. It's the end user's responsability to #
# obey alla applicable local laws. Developers assume no liability and #
# are not responible for any missue or damage caused by thi program #
########################################################################
curl http://www.md5-hash.com/md5-hashing-decrypt/$MD5 > temp.html
    sed -e 's/<[^>]*>//g' temp.html > temp.txt
    #X=$(sed -n 176,177p temp.txt)
    X=$(cat temp.txt|grep -A1 md5 )
    rm temp.html
    rm temp.txt
    if [ -n "$X" ]
    then
    result=$X
    else
    result="not found" 
    fi
    echo $result
